#%RAML 1.0
title: Booking Guru
version: v1

baseUri: https://{domain}.secure.retreat.guru/api/{version}
baseUriParameters:
  domain:
    description: The domain of the install.
mediaType:  application/json
protocols: HTTPS

/registrations:
  get:
    description: |
      Registration details including names, emails and programs people have registered to. Registrations are always sorted 
      in reverse chronological order with the newest registations are at the top or the result list.

    queryParameters:

      token:
        type: Token

      limit?:
        type: Limit

      id?:
        type: integer[]
        description: |
          Gets registrations with a specific id or list of ids. To get multiple objects, provide a comma separated list of values.

      min_date?:
        type: date-only
        description: |
          Gets registrations that were submitted on or after `min_date`. Can be combined with `max_date` for a range of dates.

      max_date?:
        type: date-only
        description: |
          Gets registrations that were submitted on or before `max_date`.

      min_stay?:
        type: date-only
        description: |
          Gets all registrations for which the registration stay dates are on or after `min_stay`. In particular
          this includes registrations that start on `min_stay`, those that start before `min_stay` and end on or after it,
          and those that start after `min_stay`. This will not include registrations that end before `min_stay`.

      max_stay?:
        type: date-only
        description: |
          Gets all registrations for which the registration stay dates are on or before `max_stay`. In particular
          this includes registrations that those that start before `max_stay` and end on or after it,
          and those that start after `max_stay`. This will not include registrations that start after `max_stay`.

      program_id?:
        type: integer
        description: |
          Gets all the registrations for a particular program unique id. You can find the id in the program list 
          of your Booking Guru admin interface in the ID column.

      program_slug?:
        type: string
        description: |
          Filter registrations by 

      nocache?:
        type: string
        description: |
          Filter registrations by 

    responses:
      200:
        description:
          An array of registration objects.
        body:
          type: Registration
      400:
        description: |
          An error message about an incorrectly submitted request. Includes deatils about the problem
          and (often) steps to follow to correct it.
        body:
          type: Error

types:
  Token:
    type: string
    description: Security token
    required: true

  Limit:
    type: integer
    description: |
      Limit number of return values. The default limit is 20. Pass `limit=0` To get all the registrations without
      limits, but please use this with caution to not overload our servers.
    required: false

  Registration:
    type: object
    properties:
      id: 
        type: integer
        description: registration id
      first_name: string
      last_name: string
      start_date: date-only
      end_date: date-only
      submitted: datetime

  Error:
    type: object
    properties:
      message: string
