#%RAML 1.0
title: Booking Guru
version: v1

baseUri: https://{domain}.secure.retreat.guru/api/{version}
baseUriParameters:
  domain:
    description: The domain of the install.
mediaType:  application/json
protocols: HTTPS

/registrations:
  get:
    description: |
      Registration details including names, emails and programs people have registered to. Registrations are always sorted 
      in reverse chronological order with the newest registrations are at the top or the result list.

    queryParameters:

      token:
        type: Token

      limit?:
        type: Limit

      id?:
        type: integer[]
        description: |
          Gets registrations with a specific id or list of ids. To get multiple objects, provide a comma separated list of values.

      min_date?:
        type: date-only
        description: |
          Gets registrations that were submitted on or after `min_date`. Can be combined with `max_date` for a range of dates.

      max_date?:
        type: date-only
        description: |
          Gets registrations that were submitted on or before `max_date`.

      min_stay?:
        type: date-only
        description: |
          Gets all registrations for which the registration stay dates are on or after `min_stay`. In particular
          this includes registrations that start on `min_stay`, those that start before `min_stay` and end on or after it,
          and those that start after `min_stay`. This will not include registrations that end before `min_stay`.

      max_stay?:
        type: date-only
        description: |
          Gets all registrations for which the registration stay dates are on or before `max_stay`. In particular
          this includes registrations that those that start before `max_stay` and end on or after it,
          and those that start after `max_stay`. This will not include registrations that start after `max_stay`.

      program_id?:
        type: integer
        description: |
          Gets all the registrations for a particular program unique id. You can find the id in the program list 
          of your Booking Guru admin interface in the ID column.

      program_slug?:
        type: string
        description: |
          Filter registrations by 

      nocache?:
        type: string
        description: |
          Filter registrations by 

    responses:
      200:
        description:
          An array of registration objects.
        body:
          type: Registration
      400:
        description: |
          An error message about an incorrectly submitted request. Includes deatils about the problem
          and (often) steps to correct it.
        body:
          type: Error

types:
  Token:
    type: string
    description: Security token
    required: true

  Limit:
    type: integer
    description: |
      Limit number of return values. The default limit is 20. Pass `limit=0` To get all the registrations without
      limits, but please use this with caution to not overload our servers.
    required: false

  Id:
    type: integer
    description: |
      Unique internal identifier of the object

  SelfUrl:
    type: string
    description: |
      A URL pointing to the object's API representation

  Registration:
    type: object
    properties:
      id: Id
      self_url: SelfUrl

      start_date:
        type: date-only
        description: Arrival date
      end_date:
        type: string
        description: Departure date
      status:
        type: string
        description: The registation status [pending, reserved, arrived, cancelled]
      first_name:
        type: string
        description: Guest's first name
      last_name:
        type: string
        description: Guest's last name
      full_name:
        type: string
        description: Guest's full name
      email:
        type: string
        description: Guest's email
      program:
        type: string
        description: The name of the program
      program_id:
        type: string
        description: 
      program_url:
        type: string
        description: 
      program_category:
        type: string
        description: 
      transactions_url:
        type: string
        description: 
      price_choice:
        type: string
        description: 
      optional_items:
        type: string
        description: 
      submitted:
        type: string
        description: 
      room_id:
        type: string
        description: 
      room:
        type: string
        description: 
      lodging_id:
        type: string
        description: 
      lodging:
        type: string
        description: 
      nights:
        type: string
        description: 
      grand_total:
        type: string
        description: 
      balance_due:
        type: string
        description: 
      subtotal_pre_tax:
        type: string
        description: 
      total_payments_refunds:
        type: string
        description: 
      taxes_sum:
        type: string
        description: 
      taxes_array:
        type: string
        description: 
      person_id:
        type: string
        description: 
      guest_statement_link:
        type: string
        description: 
      guest_edit_link:
        type: string
        description: 

  Error:
    type: object
    properties:
      message: string
